export const CURRENT_DEVICE_FETCH = 'CURRENT_DEVICE_FETCH';
export const CURRENT_DEVICE_FETCH_DONE = 'CURRENT_DEVICE_FETCH_DONE';

export const DEVICE_FETCH_ALL = 'DEVICE_FETCH_ALL';
export const DEVICE_FETCH_ALL_INIT = 'DEVICE_FETCH_ALL_INIT';
export const DEVICE_FETCH_ALL_DONE = 'DEVICE_FETCH_ALL_DONE';

export const DEVICE_CLEAR_ALL = 'DEVICE_CLEAR_ALL';
