export const SESSION_CREATE = 'SESSION_CREATE';
export const SESSION_CREATE_DONE = 'SESSION_CREATE_DONE';

export const SESSION_VALIDATE = 'SESSION_VALIDATE';
export const SESSION_INVALIDATE = 'SESSION_INVALIDATE';

export const SESSION_VERIFY = 'SESSION_VERIFY';
export const SESSION_VERIFY_DONE = 'SESSION_VERIFY_DONE';
