export const CURRENT_USER_FETCH = 'CURRENT_USER_FETCH';
export const CURRENT_USER_FETCH_DONE = 'CURRENT_USER_FETCH_DONE';

export const USER_CREATE = 'USER_CREATE';
export const USER_CREATE_DONE = 'USER_CREATE_DONE';

export const USER_FETCH_ALL = 'USER_FETCH_ALL';
export const USER_FETCH_ALL_INIT = 'USER_FETCH_ALL_INIT';
export const USER_FETCH_ALL_DONE = 'USER_FETCH_ALL_DONE';

export const USER_CLEAR_ALL = 'USER_CLEAR_ALL';
